mymoreapp/firstapp/urls.py
## Firstapp/urls.py

from django.urls import path,re_path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',index,name='first_page'),
    re_path('delete/(\d+)/',del_record,name='delete'),
    re_path('edit/(\d+)/',edit_record,name='edit')
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mymoreapp/mymoreapp/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    #127.0.01.8000
    path('',include(('firstapp.urls','firstapp'),namespace='app1')),
    
    #127.0.0.1.8000/app2/
    path('app2/',include(('secondapp.urls','secondapp'),namespace='app2'))
]

mymoreapp/secondapp/urls.py
## Secondapp/urls.py

from django.urls import path
from .views import *

urlpatterns = [
    #127.0.0.1:8000/app2
    path('',page2,name='second_page')
    
]

mymoreapp/firstapp/models.py
from django.db import models

# Create your models here.
class student(models.Model):
    name = models.CharField(max_length=10)
    course=models.CharField(max_length=20)
    email=models.EmailField()
    image=models.FileField(null=True,upload_to='pic')
    
    def __str__(self):
        return self.name
    
    

mymoreapp/secondapp/models.py
from django.db import models

# Create your models here.

mymoreapp/secondapp/forms.py
from django import forms

from firstapp.models import *

# Create your models here.
# class Post_form(forms.Form):
#     title = forms.CharField(max_length=20)
#     message = forms.CharField(widget=forms.Textarea)
   
class student_form(forms.ModelForm):
    class Meta:
        model = student
        fields = '__all__'
    
    

mymoreapp/firstapp/views.py
from django.shortcuts import render,redirect
from .models import *
# from secondapp.forms import *
from secondapp.forms import *

# Create your views here.
def index(request):
    data=student.objects.all()
    return render(request,'f1.html',{'data':data})
def del_record(request,d):
    s1=student.objects.get(id=d)
    s1.delete()
    return redirect('app1:first_page')

def edit_record(request,d):
    s1=student.objects.get(id=d)
    if request.method=='POST':
        form=student_form(request.POST,instance=s1)
        if form.is_valid():
            form.save()
            return redirect('app1:first_page')
    else:
        form = student_form(instance=s1)
        # if form.is_valid():
        #     return redirect('f1')
    return render(request,'edit.html',{'form':form})

mymoreapp/secondapp/views.py
from django.shortcuts import render, redirect
from secondapp.forms import student_form

# Create your views here.
def page2(request):
    if request.method=='POST':
        form=student_form(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('app1:first_page')
    else:
        form = student_form()
        # if form.is_valid():
        #     return redirect('f1')
    return render(request,'home.html',{'form':form})
# def index(request):
#     data=student.objects.all()
#     return render(request,'f1.html',{'d':data})
   

mymoreapp/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Edit record</h1>
    <form action='' method='post' enctype="multipart/form-data">{% csrf_token %}
        {{form.as_p}}
        <input type='submit' value='submit'/>
    </form>
    
    <a href="{% url 'app1:first_page' %}">click here for first page</a>
</body>
</html>

mymoreapp/templates/f1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Students Details !!</h1>
   
    {% for k in data %}
    {% if k.image %}
    
    <img src="{{k.image.url}}" width="100px" height="100px">
    {% endif %}
    <p>Id:{{k.id}}</p>
    <p>Name:{{k.name}}</p>
    <p>course:{{k.course}}</p>
    <p>Email:{{k.email}}</p>
    
    <a href="{% url 'app1:delete' k.id %}">Delete record</a>
    <br>
    <a href="{% url 'app1:edit' k.id %}">Edit record</a>
    <hr>
    {% endfor %}
    
    <br>
    
    
    <a href="{% url 'app2:second_page' %}">Click here Add record</a>
</body>
</html>

mymoreapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>resitration form for Student</h1>
    <form action='' method='post' enctype="multipart/form-data">{% csrf_token %}
        {{form.as_p}}
        <input type='submit' value='submit'/>
    </form>
    
    <a href="{% url 'app1:first_page' %}">click here for first page</a>
</body>
</html>